version: "3.0"
services:

  pg-1:
    image: docker.io/bitnami/postgresql-repmgr:latest
    container_name: pg-1
    volumes:
      - sd01-pg_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-1
      # list of all postgres nodes
      - REPMGR_PARTNER_NODES=pg-1,pg-2,pg-9
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
    networks:
      - database
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
         - node.hostname==sd01
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 2
        window: 60s

  pg-2:
    image: docker.io/bitnami/postgresql-repmgr:latest
    container_name: pg-1
    volumes:
      - sd02-pg_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-1
      # list of all postgres nodes
      - REPMGR_PARTNER_NODES=pg-1,pg-2,pg-9
      - REPMGR_NODE_NAME=pg-2
      - REPMGR_NODE_NETWORK_NAME=pg-2
    networks:
      - database
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
         - node.hostname==sd02
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 2
        window: 60s

  pg-9:
    image: docker.io/bitnami/postgresql-repmgr:latest
    container_name: pg-2
    ports:
      - 15432:5432
    volumes:
      - reporting-pg_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-1
      # list of all postgres nodes
      - REPMGR_PARTNER_NODES=pg-1,pg-2,pg-9
      - REPMGR_NODE_NAME=pg-9
      - REPMGR_NODE_NETWORK_NAME=pg-9
    networks:
      - database
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
         - node.hostname==fsreports
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 2
        window: 60s

  pgpool:
    image: docker.io/bitnami/pgpool:4
    container_name: pgpool
    ports:
      - 5432:5432
    environment:
      # update list with node names followed by :5432 #
      - PGPOOL_BACKEND_NODES=0:pg-2:5432,1:pg-1:5432,pg-9:5432
      # end update #
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=custompassword
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=adminpassword
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - database
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
         - node.hostname==sd01
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 2
        window: 60s

networks:
    database:

volumes:
  sd01-pg_data:
    driver: local
  sd02-pg_data:
    driver: local
  reporting-pg_data:
    driver: local