version: "3.0"
services:
  sd01:
    image: docker.io/bitnami/postgresql-repmgr:latest
    volumes:
      - sd01-pg_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=sd01
      # list of all postgres nodes
      - REPMGR_PARTNER_NODES=sd01,sd02,sd99
      - REPMGR_NODE_NAME=sd01
      - REPMGR_NODE_NETWORK_NAME=sd01
    networks:
      - ACCESS
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
         - node.hostname==sd01
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 2
        window: 60s

networks:
  ACCESS:
    external: true
volumes:
  sd01-pg_data:
    driver: local

